/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/
#ifndef ROOSTUDENTT
#define ROOSTUDENTT
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
class RooStudentT : public RooAbsPdf
{
public:
	RooStudentT() {}
	RooStudentT(const char *name, const char *title, RooAbsReal& _m, RooAbsReal& _m0, RooAbsReal& _sigma, RooAbsReal& _nu);
	RooStudentT(const RooStudentT& other, const char* name=0);
	virtual TObject* clone(const char* newname) const { return new RooStudentT(*this,newname); }
	inline virtual ~RooStudentT() {}
protected:
	RooRealProxy m;
	RooRealProxy m0;
	RooRealProxy sigma;
	RooRealProxy nu;
	Double_t evaluate() const;
private:
	ClassDef(RooStudentT,2)
};
#endif
